apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
spec:
  replicas: 5
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: canary-demo
  template:
    metadata:
      labels:
        app: canary-demo
    spec:
      containers:
        - name: canary-demo
          image: argoproj/rollouts-demo:green
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
  strategy:
    canary:
      canaryService: canary-demo-preview
      stableService: canary-demo
      trafficRouting:
        nginx:
          stableIngress: canary-demo
          additionalIngressAnnotations:
            nginx.ingress.kubernetes.io/canary: "true"
      steps:
        - setCanaryScale:
            replicas: 1
        - analysis:
            metrics:
              - name: eservice-task-job
                provider:
                  job:
                    spec:
                      backoffLimit: 1
                      template:
                        spec:
                          containers:
                            - name: job
                              image: ticket-generator:1.0.0
                          restartPolicy: Never
        - pause: {}
        - setWeight: 100
